# Generated by Django 4.1.7 on 2023-03-13 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(blank=True, default='./static/assets/media/blog/default_userpp.jpg', null=True, upload_to='avatar/'),
        ),
    ]
