# Generated by Django 4.1.7 on 2023-03-22 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_settings_facebook_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='email',
            field=models.EmailField(blank=True, max_length=200, null=True),
        ),
    ]
