# Generated by Django 4.1.7 on 2023-03-27 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_alter_blog_category_alter_blog_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='special_content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
