# Generated by Django 4.1.7 on 2023-03-27 20:46

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_blog_special_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='blog',
            name='special_content',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
