# Generated by Django 4.1.7 on 2023-03-29 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_alter_blog_description_alter_blog_special_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='videopost',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
