# Generated by Django 4.1.7 on 2023-05-13 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_services'),
    ]

    operations = [
        migrations.CreateModel(
            name='Services_category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Services Category',
            },
        ),
    ]
