# Generated by Django 4.1.7 on 2023-05-13 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_services_description_az_services_description_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='services_category',
            name='title_az',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='services_category',
            name='title_en',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
