# Generated by Django 4.1.7 on 2023-05-13 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_services_category_title_az_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='special_content',
        ),
    ]
